from __future__ import annotations

from dataclasses import dataclass

from .models import SEVERITY_RANK, ScanReport


@dataclass(frozen=True)
class Decision:
    action: str
    label: str
    title: str
    request_changes: bool
    comment: bool


def decide(
    report: ScanReport,
    approve_label: str = "security/approved",
    block_label: str = "security/blocked",
    review_label: str = "security/review",
    comment_on_approval: bool = False,
) -> Decision:
    rank = SEVERITY_RANK[report.max_severity]
    if rank >= SEVERITY_RANK["HIGH"]:
        return Decision(
            action="block",
            label=block_label,
            title="Security risk blocked",
            request_changes=True,
            comment=True,
        )
    if rank >= SEVERITY_RANK["MEDIUM"]:
        return Decision(
            action="review",
            label=review_label,
            title="Security review required",
            request_changes=False,
            comment=True,
        )
    return Decision(
        action="approve",
        label=approve_label,
        title="Security approved",
        request_changes=False,
        comment=comment_on_approval,
    )


def render_comment(report: ScanReport, decision: Decision) -> str:
    lines = [
        "### OSS Sentinel Bot",
        "",
        f"Decision: **{decision.title}**",
        f"Scanner: `{report.scanner}`",
        f"Max severity: `{report.max_severity}`",
        "",
        report.summary or "No summary provided.",
    ]
    if report.findings:
        lines.extend(
            [
                "",
                "| Severity | Path | Line | Category | Finding |",
                "| --- | --- | ---: | --- | --- |",
            ]
        )
        for finding in report.findings[:10]:
            line = "" if finding.line is None else str(finding.line)
            path = finding.path or "-"
            lines.append(
                f"| {finding.severity} | `{path}` | {line} | {finding.category} | {finding.message} |"
            )
        if len(report.findings) > 10:
            lines.append(f"| INFO | - |  | truncated | {len(report.findings) - 10} more finding(s) omitted |")
        lines.extend(["", "Recommended next actions:"])
        for finding in report.findings[:5]:
            lines.append(f"- `{finding.path or 'repository'}`: {finding.recommendation}")
    else:
        lines.extend(["", "No findings were produced by the configured scan path."])
    lines.extend(["", "_Generated by OSS Sentinel Bot._"])
    return "\n".join(lines)

